"""added r2_key column to databse

Revision ID: 2e6a294fcbe7
Revises: 6bd03012ac51
Create Date: 2026-04-15 23:32:37.533520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6a294fcbe7'
down_revision: Union[str, Sequence[str], None] = '6bd03012ac51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_documents')
    op.add_column('documents', sa.Column('r2_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'r2_key')
    op.create_table('chat_documents',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('chat_documents_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('chat_documents_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'document_id', name=op.f('chat_documents_pkey'))
    )
    # ### end Alembic commands ###
