"""fixed column name

Revision ID: 68f65b386808
Revises: 2e6a294fcbe7
Create Date: 2026-04-16 10:36:13.109865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f65b386808'
down_revision: Union[str, Sequence[str], None] = '2e6a294fcbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
