"""remove parent message id

Revision ID: 6bd03012ac51
Revises: 993dd731bea9
Create Date: 2026-02-17 08:34:18.889221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd03012ac51'
down_revision: Union[str, Sequence[str], None] = '993dd731bea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_parent_message_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_parent_message_id_fkey'), 'messages', 'messages', ['parent_message_id'], ['id'])
    # ### end Alembic commands ###
