"""added columns to document database

Revision ID: 993dd731bea9
Revises: c2216ceccf54
Create Date: 2026-02-15 00:39:44.659622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '993dd731bea9'
down_revision: Union[str, Sequence[str], None] = 'c2216ceccf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_documents')
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('upload_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('documents', 'upload_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('documents', 'upload_time')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'content_type')
    op.create_table('chat_documents',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('chat_documents_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('chat_documents_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'document_id', name=op.f('chat_documents_pkey'))
    )
    # ### end Alembic commands ###
