"""initial rivision, create/update schemas

Revision ID: c2216ceccf54
Revises: 
Create Date: 2026-02-13 18:54:41.612247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2216ceccf54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_message_id')
    # ### end Alembic commands ###
